# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]  # It's better to use LTS versions unless you specifically need Node.js 20.x

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Change to project directory  # Make sure we're in the right directory
      run: cd ChefPage

    - name: Install Dependencies
      run: npm ci  # This is preferable for CI/CD as it uses the lock file strictly

    - name: Build the project
      run: npm run build --if-present

    - name: Run Tests
      run: npm test

    - name: Deploy with gh-pages
      run: |
        git config --global user.email "support+actions@github.com"
        git config --global user.name "github-actions-bot"
        git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ GITHUB_REPOSITORY }}.git
        npx gh-pages -d build -b master -e "ChefPage"  # deploy from build directory
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}